stages:
  - build
  - deploy
  - delivery

cache:
  paths:
    - .build

build:
  stage: build
  before_script:
    - cd $(go env GOPATH)/src
    - mkdir -p tingtt.gitlab.com/$CI_PROJECT_NAMESPACE
    - cd tingtt.gitlab.com/$CI_PROJECT_NAMESPACE
    - ln -s $CI_PROJECT_DIR || true
    - cd $CI_PROJECT_NAME
  script:
    - make

deploy:
  stage: deploy
  only:
    - main
  before_script:
    - sudo apt install -y openssh-client
    - eval "$(ssh-agent -s)"
    - echo "$DEPLOY_SSH_SECRET" | tr -d '\r' | ssh-add -
    - >
      ssh "$DEPLOY_HOST_SSH_USER"@"$DEPLOY_HOST" -p "$DEPLOY_HOST_SSH_PORT" 'sudo systemctl stop prometheus_sh_exporter.service || true &&
        mkdir -p ~/prometheus_sh_exporter &&
        rm -rf ~/prometheus_sh_exporter/*'
    - scp -r -P "$DEPLOY_HOST_SSH_PORT" Makefile .build prometheus_sh_exporter.service sh.yml commands "$DEPLOY_HOST_SSH_USER"@"$DEPLOY_HOST":~/prometheus_sh_exporter/
  script:
    - >
      ssh "$DEPLOY_HOST_SSH_USER"@"$DEPLOY_HOST" -p "$DEPLOY_HOST_SSH_PORT" 'cd ~/prometheus_sh_exporter &&
        sudo make install &&
        sudo systemctl start prometheus_sh_exporter.service &&
        sudo systemctl status prometheus_sh_exporter.service'

push-github:
  stage: delivery
  only:
    - main
    - tags
  before_script:
    - sudo apt install -y openssh-client
    - eval "$(ssh-agent -s)"
    - echo "$GITHUB_SSH_SECRET" | tr -d '\r' | ssh-add -
    - git config --local user.name "$GITHUB_USER"
    - git config --local user.email "$GITHUB_EMAIL"
    - git remote add github "$GITHUB_REMOTE_URL" || true
  script:
    - git branch main || git checkout main
    - git pull origin main -r
    - git push github main -f --tags
